name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [wp-build]

jobs:
  deploy:
    uses: hiep-dev-023/shared-workflows/.github/workflows/deploy-ftp.yml@main
    with:
      project-name: template_jline_html
      server-ftp: jline
      local-dir: public/
    secrets: inherit